### ISSUE TITLE
Demo worker exits with code 2 making it impossible to run migration

### ISSUE THREAD

**Issue by ssteinerx** [TomasTomecek/open-house-2016-demo#1]
Doing as little as possible to get this going -- just 

```
docker-compose up
```

And I get this in the terminal::

```
openhouse2016demo_web_1 exited with code 2
openhouse2016demo_worker_1 exited with code 2
worker_1  | python: can't open file '/opt/app/channels-example/manage.py': [Errno 2] No such file or directory
worker_1  | python: can't open file '/opt/app/channels-example/manage.py': [Errno 2] No such file or directory
worker_1  | python: can't open file '/opt/app/channels-example/manage.py': [Errno 2] No such file or directory
web_1     | python: can't open file '/opt/app/channels-example/manage.py': [Errno 2] No such file or directory
web_1     | python: can't open file '/opt/app/channels-example/manage.py': [Errno 2] No such file or directory
web_1     | python: can't open file '/opt/app/channels-example/manage.py': [Errno 2] No such file or directory
```

**Comment by ssteinerx** [comment]
The problem is that you map /opt/app to the local directory, then clone into the directory in the container.  The channels-example directory gets created on the local machine, but it's empty.

IOW, this relies on there being a checkout of the channels-example project _in your local directory_.

I'm sure that was the case on your demo setup, but not the case (is now) on my machine.

There's no reason to check the project out to the container if your intention is to use the copy on the local machine.

I would patch the Dockerfile and such, but I'm totally unfamiliar with Fedora.  I use alpine for the base of most everything as it's ~5mb and am not familiar with the Fedora package system etc.

**Comment by TomasTomecek** [comment]
The readme file clearly states that you should clone the project first and then run `docker-compose up`. I agree that's suboptimal. I'm going to fix this.

Thanks for suggestion.
