### ISSUE TITLE
DB server doesn't get going fast enough for Django's startup

### ISSUE THREAD

**Issue by ssteinerx** [TomasTomecek/open-house-2016-demo#2]
db_1      | loading PL/pgSQL server-side language ... ok
web_1     | Unhandled exception in thread started by <function wrapper at 0x7fba0b70fc80>
web_1     | Traceback (most recent call last):
web_1     |   File "/usr/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
web_1     |     fn(_args, *_kwargs)

The database server hasn't gotten off the ground in time for Django to talk to it.

You can get it to restart by meaningfully touching a file on the local channels-example checkout.

I'm not going to mess with this as it's based on a 'wild' Fedora base I'm not familiar with even far beyond not being a Fedora user.

**Comment by TomasTomecek** [comment]
This is a very good point. Luckily it has a very easy workaround: restart web after you know that database is up.

Unfortunately there's no "easy & right" way to fix this. Will try anyway.
