### ISSUE TITLE
Example for deploying to AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by jasjuang** [TomasTomecek/open-house-2016-demo#4]
Hi Tomas,

Thanks for putting up the dockerized version of this app. I am able to successfully run it locally on my machine but I am having trouble deploying it to AWS. I was wondering could you give us some instructions on how to deploy this via AWS Elastic Beanstalk with the "multi-container docker" option?

Thanks,
Jason

**Comment by TomasTomecek** [comment]
Hey Jason, the truth is that I have never used that service so I literally have no idea how to do that. Ideally, you should be able to take `docker-compose.yml` and "translate" it into configuration the service is using.

**Comment by jasjuang** [comment]
Got it. Another question I have is I realize you didn't use nginx or apache, is "runserver" good for production? I know it isn't for traditional wsgi apps but I am not sure for asgi channel apps.

**Comment by TomasTomecek** [comment]
It's definitely not for production:

https://docs.djangoproject.com/en/1.10/ref/django-admin/#runserver

I would suggest uwsgi or gunicorn, not sure if those can handle the new asgi protocol.

**Comment by jasjuang** [comment]
Thanks a lot for the answer!
